# Generated by https://quicktype.io

from typing import List


class Coord:
    latitude: float
    longitude: float

    def __init__(self, latitude: float, longitude: float) -> None:
        self.latitude = latitude
        self.longitude = longitude


class Location:
    coords: List[Coord]
    type: str
    num_spots: int
    id: int

    def __init__(self, coords: List[Coord], type: str, num_spots: int, id: int) -> None:
        self.coords = coords
        self.type = type
        self.num_spots = num_spots
        self.id = id


class Park:
    locations: List[Location]

    def __init__(self, locations: List[Location]) -> None:
        self.locations = locations